// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyblock.sql

package database

import (
	"context"
)

const copyBlock = `-- name: CopyBlock :one
BEGIN
`

type CopyBlockRow struct {
}

func (q *Queries) CopyBlock(ctx context.Context) (CopyBlockRow, error) {
	row := q.db.QueryRowContext(ctx, copyBlock)
	var i CopyBlockRow
	err := row.Scan()
	return i, err
}
