// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getblock.sql

package database

import (
	"context"
	"database/sql"
)

const getBlock = `-- name: GetBlock :one
SELECT blockhash, confirmations, height, version, version_hex, merkle_root, time, median_time, nonce, bits, difficulty, chainwork, ntx, previous_block_hash, next_block_hash, stripped_size, size, weight FROM blocks WHERE blockhash=$1
`

func (q *Queries) GetBlock(ctx context.Context, blockhash sql.NullString) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlock, blockhash)
	var i Block
	err := row.Scan(
		&i.Blockhash,
		&i.Confirmations,
		&i.Height,
		&i.Version,
		&i.VersionHex,
		&i.MerkleRoot,
		&i.Time,
		&i.MedianTime,
		&i.Nonce,
		&i.Bits,
		&i.Difficulty,
		&i.Chainwork,
		&i.Ntx,
		&i.PreviousBlockHash,
		&i.NextBlockHash,
		&i.StrippedSize,
		&i.Size,
		&i.Weight,
	)
	return i, err
}
