// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gethighestblock.sql

package database

import (
	"context"
	"database/sql"
)

const getHighestBlock = `-- name: GetHighestBlock :one
SELECT height FROM blocks ORDER BY height DESC
`

func (q *Queries) GetHighestBlock(ctx context.Context) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getHighestBlock)
	var height sql.NullInt32
	err := row.Scan(&height)
	return height, err
}
