// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Block struct {
	Blockhash         sql.NullString
	Confirmations     sql.NullInt32
	Height            sql.NullInt32
	Version           sql.NullInt32
	VersionHex        sql.NullString
	MerkleRoot        sql.NullString
	Time              sql.NullTime
	MedianTime        sql.NullTime
	Nonce             sql.NullInt32
	Bits              sql.NullString
	Difficulty        sql.NullString
	Chainwork         sql.NullString
	Ntx               sql.NullInt32
	PreviousBlockHash sql.NullString
	NextBlockHash     sql.NullString
	StrippedSize      sql.NullInt32
	Size              sql.NullInt32
	Weight            sql.NullInt32
}

type Transaction struct {
	Txid         sql.NullString
	Hash         sql.NullString
	Segwit       sql.NullBool
	ReplaceByFee sql.NullBool
	Version      sql.NullInt32
	Size         sql.NullInt32
	Vsize        sql.NullInt32
	Weight       sql.NullInt32
	Locktime     sql.NullInt32
	Fee          sql.NullString
	Hex          sql.NullString
	Blockhash    sql.NullString
	Blockheight  sql.NullInt32
	Time         sql.NullTime
}

type Vin struct {
	Txid                sql.NullString
	PrevTxid            sql.NullString
	Coinbase            sql.NullString
	Vout                sql.NullInt32
	ScriptsigAsm        sql.NullString
	ScriptsigHex        sql.NullString
	Txinwitness         []string
	PrevBlockheight     sql.NullInt32
	Value               sql.NullString
	ScriptPubkeyAsm     sql.NullString
	ScriptPubkeyDesc    sql.NullString
	ScriptPubkeyHex     sql.NullString
	ScriptPubkeyAddress sql.NullString
	ScriptPubkeyType    sql.NullString
	Sequence            sql.NullInt32
}

type Vout struct {
	Txid                sql.NullString
	Value               sql.NullString
	N                   sql.NullInt32
	ScriptPubkeyAsm     sql.NullString
	ScriptPubkeyDesc    sql.NullString
	ScriptPubkeyHex     sql.NullString
	ScriptPubkeyAddress sql.NullString
	ScriptPubkeyType    sql.NullString
}
