// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: updateblock.sql

package database

import (
	"context"
	"database/sql"
)

const updateBlock = `-- name: UpdateBlock :one
UPDATE blocks 
SET completed=$2
WHERE blockhash=$1
RETURNING blockhash,completed
`

type UpdateBlockParams struct {
	Blockhash string
	Completed sql.NullBool
}

type UpdateBlockRow struct {
	Blockhash string
	Completed sql.NullBool
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) (UpdateBlockRow, error) {
	row := q.db.QueryRowContext(ctx, updateBlock, arg.Blockhash, arg.Completed)
	var i UpdateBlockRow
	err := row.Scan(&i.Blockhash, &i.Completed)
	return i, err
}
